// <auto-generated />
using System;
using MachineMonitoring.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MachineMonitoring.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MachineMonitoringDbContext))]
    [Migration("20260715063148_AddMachineCapabilities")]
    partial class AddMachineCapabilities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MachineMonitoring.Domain.Technology.DrawingFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256_hash");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stored_file_name");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id");

                    b.HasIndex("StoredFileName")
                        .IsUnique();

                    b.ToTable("drawing_files", (string)null);
                });

            modelBuilder.Entity("MachineMonitoring.Domain.Technology.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("grade");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("materials", (string)null);
                });

            modelBuilder.Entity("MachineMonitoring.Domain.Technology.Nozzle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<decimal>("DiameterMillimeters")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("diameter_millimeters");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<decimal>("MaximumPressureBar")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("maximum_pressure_bar");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<decimal>("WearPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("wear_percentage");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("nozzles", (string)null);
                });

            modelBuilder.Entity("MachineMonitoring.Infrastructure.Persistence.Models.MachineCapabilitiesRecord", b =>
                {
                    b.Property<string>("MachineId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("machine_id");

                    b.Property<decimal>("MaximumLaserPowerWatts")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("maximum_laser_power_watts");

                    b.Property<decimal?>("MaximumSheetHeightMillimeters")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("maximum_sheet_height_millimeters");

                    b.Property<decimal?>("MaximumSheetWidthMillimeters")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("maximum_sheet_width_millimeters");

                    b.Property<decimal>("MaximumThicknessMillimeters")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("maximum_thickness_millimeters");

                    b.Property<decimal?>("MaximumTubeDiameterMillimeters")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("maximum_tube_diameter_millimeters");

                    b.Property<decimal?>("MaximumTubeLengthMillimeters")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("maximum_tube_length_millimeters");

                    b.Property<decimal>("MinimumThicknessMillimeters")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("minimum_thickness_millimeters");

                    b.HasKey("MachineId");

                    b.ToTable("machine_capabilities", (string)null);
                });

            modelBuilder.Entity("MachineMonitoring.Infrastructure.Persistence.Models.MachineCapabilityGeometryTypeRecord", b =>
                {
                    b.Property<string>("MachineId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("machine_id");

                    b.Property<string>("GeometryType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("geometry_type");

                    b.HasKey("MachineId", "GeometryType");

                    b.ToTable("machine_capability_geometry_types", (string)null);
                });

            modelBuilder.Entity("MachineMonitoring.Infrastructure.Persistence.Models.MachineCapabilityMaterialCategoryRecord", b =>
                {
                    b.Property<string>("MachineId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("machine_id");

                    b.Property<string>("MaterialCategory")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("material_category");

                    b.HasKey("MachineId", "MaterialCategory");

                    b.ToTable("machine_capability_material_categories", (string)null);
                });

            modelBuilder.Entity("MachineMonitoring.Infrastructure.Persistence.Models.MachineCapabilityNozzleRecord", b =>
                {
                    b.Property<string>("MachineId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("machine_id");

                    b.Property<Guid>("NozzleId")
                        .HasColumnType("uuid")
                        .HasColumnName("nozzle_id");

                    b.HasKey("MachineId", "NozzleId");

                    b.HasIndex("NozzleId");

                    b.ToTable("machine_capability_nozzles", (string)null);
                });

            modelBuilder.Entity("MachineMonitoring.Infrastructure.Persistence.Models.MachineCapabilityGeometryTypeRecord", b =>
                {
                    b.HasOne("MachineMonitoring.Infrastructure.Persistence.Models.MachineCapabilitiesRecord", "MachineCapabilities")
                        .WithMany("SupportedGeometryTypes")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MachineCapabilities");
                });

            modelBuilder.Entity("MachineMonitoring.Infrastructure.Persistence.Models.MachineCapabilityMaterialCategoryRecord", b =>
                {
                    b.HasOne("MachineMonitoring.Infrastructure.Persistence.Models.MachineCapabilitiesRecord", "MachineCapabilities")
                        .WithMany("SupportedMaterialCategories")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MachineCapabilities");
                });

            modelBuilder.Entity("MachineMonitoring.Infrastructure.Persistence.Models.MachineCapabilityNozzleRecord", b =>
                {
                    b.HasOne("MachineMonitoring.Infrastructure.Persistence.Models.MachineCapabilitiesRecord", "MachineCapabilities")
                        .WithMany("SupportedNozzles")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MachineMonitoring.Domain.Technology.Nozzle", null)
                        .WithMany()
                        .HasForeignKey("NozzleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MachineCapabilities");
                });

            modelBuilder.Entity("MachineMonitoring.Infrastructure.Persistence.Models.MachineCapabilitiesRecord", b =>
                {
                    b.Navigation("SupportedGeometryTypes");

                    b.Navigation("SupportedMaterialCategories");

                    b.Navigation("SupportedNozzles");
                });
#pragma warning restore 612, 618
        }
    }
}
