// <auto-generated />
using System;
using MachineMonitoring.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MachineMonitoring.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MachineMonitoringDbContext))]
    [Migration("20260717063627_AddOperationEventsAndMachineAlarms")]
    partial class AddOperationEventsAndMachineAlarms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MachineMonitoring.Domain.Technology.DrawingFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256_hash");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stored_file_name");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id");

                    b.HasIndex("StoredFileName")
                        .IsUnique();

                    b.ToTable("drawing_files", (string)null);
                });

            modelBuilder.Entity("MachineMonitoring.Domain.Technology.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("grade");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("materials", (string)null);
                });

            modelBuilder.Entity("MachineMonitoring.Domain.Technology.Nozzle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<decimal>("DiameterMillimeters")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("diameter_millimeters");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<decimal>("MaximumPressureBar")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("maximum_pressure_bar");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<decimal>("WearPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("wear_percentage");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("nozzles", (string)null);
                });

            modelBuilder.Entity("MachineMonitoring.Infrastructure.Persistence.Models.LaserCutConfigurationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssistGas")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("assist_gas");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CuttingSpeedMillimetersPerMinute")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("cutting_speed_millimeters_per_minute");

                    b.Property<Guid>("DrawingFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("drawing_file_id");

                    b.Property<decimal>("FocalOffsetMillimeters")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("focal_offset_millimeters");

                    b.Property<decimal>("GasPressureBar")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("gas_pressure_bar");

                    b.Property<string>("GeometryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("geometry_type");

                    b.Property<decimal>("LaserPowerWatts")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("laser_power_watts");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<Guid>("NozzleId")
                        .HasColumnType("uuid")
                        .HasColumnName("nozzle_id");

                    b.Property<int>("NumberOfPasses")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_passes");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<decimal?>("SheetHeightMillimeters")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("sheet_height_millimeters");

                    b.Property<decimal?>("SheetWidthMillimeters")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("sheet_width_millimeters");

                    b.Property<decimal>("ThicknessMillimeters")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("thickness_millimeters");

                    b.Property<decimal?>("TubeLengthMillimeters")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("tube_length_millimeters");

                    b.Property<decimal?>("TubeOuterDiameterMillimeters")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("tube_outer_diameter_millimeters");

                    b.HasKey("Id");

                    b.HasIndex("DrawingFileId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("NozzleId");

                    b.HasIndex("OperationId")
                        .IsUnique();

                    b.ToTable("laser_cut_configurations", (string)null);
                });

            modelBuilder.Entity("MachineMonitoring.Infrastructure.Persistence.Models.MachineAlarmRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("machine_id");

                    b.Property<Guid?>("MachineOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("machine_operation_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset>("RaisedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("raised_at");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("resolution_notes");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("MachineOperationId");

                    b.HasIndex("Status");

                    b.HasIndex("MachineId", "Status");

                    b.ToTable("machine_alarms", (string)null);
                });

            modelBuilder.Entity("MachineMonitoring.Infrastructure.Persistence.Models.MachineCapabilitiesRecord", b =>
                {
                    b.Property<string>("MachineId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("machine_id");

                    b.Property<decimal>("MaximumLaserPowerWatts")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("maximum_laser_power_watts");

                    b.Property<decimal?>("MaximumSheetHeightMillimeters")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("maximum_sheet_height_millimeters");

                    b.Property<decimal?>("MaximumSheetWidthMillimeters")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("maximum_sheet_width_millimeters");

                    b.Property<decimal>("MaximumThicknessMillimeters")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("maximum_thickness_millimeters");

                    b.Property<decimal?>("MaximumTubeDiameterMillimeters")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("maximum_tube_diameter_millimeters");

                    b.Property<decimal?>("MaximumTubeLengthMillimeters")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("maximum_tube_length_millimeters");

                    b.Property<decimal>("MinimumThicknessMillimeters")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("minimum_thickness_millimeters");

                    b.HasKey("MachineId");

                    b.ToTable("machine_capabilities", (string)null);
                });

            modelBuilder.Entity("MachineMonitoring.Infrastructure.Persistence.Models.MachineCapabilityGeometryTypeRecord", b =>
                {
                    b.Property<string>("MachineId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("machine_id");

                    b.Property<string>("GeometryType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("geometry_type");

                    b.HasKey("MachineId", "GeometryType");

                    b.ToTable("machine_capability_geometry_types", (string)null);
                });

            modelBuilder.Entity("MachineMonitoring.Infrastructure.Persistence.Models.MachineCapabilityMaterialCategoryRecord", b =>
                {
                    b.Property<string>("MachineId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("machine_id");

                    b.Property<string>("MaterialCategory")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("material_category");

                    b.HasKey("MachineId", "MaterialCategory");

                    b.ToTable("machine_capability_material_categories", (string)null);
                });

            modelBuilder.Entity("MachineMonitoring.Infrastructure.Persistence.Models.MachineCapabilityNozzleRecord", b =>
                {
                    b.Property<string>("MachineId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("machine_id");

                    b.Property<Guid>("NozzleId")
                        .HasColumnType("uuid")
                        .HasColumnName("nozzle_id");

                    b.HasKey("MachineId", "NozzleId");

                    b.HasIndex("NozzleId");

                    b.ToTable("machine_capability_nozzles", (string)null);
                });

            modelBuilder.Entity("MachineMonitoring.Infrastructure.Persistence.Models.MachineOperationEventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<Guid?>("MachineAlarmId")
                        .HasColumnType("uuid")
                        .HasColumnName("machine_alarm_id");

                    b.Property<Guid>("MachineOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("machine_operation_id");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("new_status");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Phase")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("phase");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("previous_status");

                    b.Property<int?>("ProgressPercentage")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percentage");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("MachineAlarmId");

                    b.HasIndex("MachineOperationId", "OccurredAt");

                    b.ToTable("machine_operation_events", (string)null);
                });

            modelBuilder.Entity("MachineMonitoring.Infrastructure.Persistence.Models.MachineOperationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentPhase")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("current_phase");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("machine_id");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percentage");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<Guid>("WorkpieceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workpiece_id");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("Status");

                    b.HasIndex("WorkpieceId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("WorkpieceId", "Status", "SequenceNumber");

                    b.ToTable("machine_operations", (string)null);
                });

            modelBuilder.Entity("MachineMonitoring.Infrastructure.Persistence.Models.ProductionLotRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("PlannedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("planned_quantity");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("production_lots", (string)null);
                });

            modelBuilder.Entity("MachineMonitoring.Infrastructure.Persistence.Models.WorkpieceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsSequenceActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sequence_active");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("material_code");

                    b.Property<Guid>("ProductionLotId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_lot_id");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ProductionLotId");

                    b.HasIndex("Status");

                    b.HasIndex("ProductionLotId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("ProductionLotId", "Status", "SequenceNumber");

                    b.ToTable("workpieces", (string)null);
                });

            modelBuilder.Entity("MachineMonitoring.Infrastructure.Persistence.Models.LaserCutConfigurationRecord", b =>
                {
                    b.HasOne("MachineMonitoring.Domain.Technology.DrawingFile", null)
                        .WithMany()
                        .HasForeignKey("DrawingFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MachineMonitoring.Domain.Technology.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MachineMonitoring.Domain.Technology.Nozzle", null)
                        .WithMany()
                        .HasForeignKey("NozzleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MachineMonitoring.Infrastructure.Persistence.Models.MachineOperationRecord", "Operation")
                        .WithOne("LaserCutConfiguration")
                        .HasForeignKey("MachineMonitoring.Infrastructure.Persistence.Models.LaserCutConfigurationRecord", "OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("MachineMonitoring.Infrastructure.Persistence.Models.MachineAlarmRecord", b =>
                {
                    b.HasOne("MachineMonitoring.Infrastructure.Persistence.Models.MachineOperationRecord", "MachineOperation")
                        .WithMany("MachineAlarms")
                        .HasForeignKey("MachineOperationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MachineOperation");
                });

            modelBuilder.Entity("MachineMonitoring.Infrastructure.Persistence.Models.MachineCapabilityGeometryTypeRecord", b =>
                {
                    b.HasOne("MachineMonitoring.Infrastructure.Persistence.Models.MachineCapabilitiesRecord", "MachineCapabilities")
                        .WithMany("SupportedGeometryTypes")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MachineCapabilities");
                });

            modelBuilder.Entity("MachineMonitoring.Infrastructure.Persistence.Models.MachineCapabilityMaterialCategoryRecord", b =>
                {
                    b.HasOne("MachineMonitoring.Infrastructure.Persistence.Models.MachineCapabilitiesRecord", "MachineCapabilities")
                        .WithMany("SupportedMaterialCategories")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MachineCapabilities");
                });

            modelBuilder.Entity("MachineMonitoring.Infrastructure.Persistence.Models.MachineCapabilityNozzleRecord", b =>
                {
                    b.HasOne("MachineMonitoring.Infrastructure.Persistence.Models.MachineCapabilitiesRecord", "MachineCapabilities")
                        .WithMany("SupportedNozzles")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MachineMonitoring.Domain.Technology.Nozzle", null)
                        .WithMany()
                        .HasForeignKey("NozzleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MachineCapabilities");
                });

            modelBuilder.Entity("MachineMonitoring.Infrastructure.Persistence.Models.MachineOperationEventRecord", b =>
                {
                    b.HasOne("MachineMonitoring.Infrastructure.Persistence.Models.MachineAlarmRecord", "MachineAlarm")
                        .WithMany("OperationEvents")
                        .HasForeignKey("MachineAlarmId");

                    b.HasOne("MachineMonitoring.Infrastructure.Persistence.Models.MachineOperationRecord", "MachineOperation")
                        .WithMany("Events")
                        .HasForeignKey("MachineOperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MachineAlarm");

                    b.Navigation("MachineOperation");
                });

            modelBuilder.Entity("MachineMonitoring.Infrastructure.Persistence.Models.MachineOperationRecord", b =>
                {
                    b.HasOne("MachineMonitoring.Infrastructure.Persistence.Models.WorkpieceRecord", "Workpiece")
                        .WithMany("Operations")
                        .HasForeignKey("WorkpieceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workpiece");
                });

            modelBuilder.Entity("MachineMonitoring.Infrastructure.Persistence.Models.WorkpieceRecord", b =>
                {
                    b.HasOne("MachineMonitoring.Infrastructure.Persistence.Models.ProductionLotRecord", "ProductionLot")
                        .WithMany("Workpieces")
                        .HasForeignKey("ProductionLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionLot");
                });

            modelBuilder.Entity("MachineMonitoring.Infrastructure.Persistence.Models.MachineAlarmRecord", b =>
                {
                    b.Navigation("OperationEvents");
                });

            modelBuilder.Entity("MachineMonitoring.Infrastructure.Persistence.Models.MachineCapabilitiesRecord", b =>
                {
                    b.Navigation("SupportedGeometryTypes");

                    b.Navigation("SupportedMaterialCategories");

                    b.Navigation("SupportedNozzles");
                });

            modelBuilder.Entity("MachineMonitoring.Infrastructure.Persistence.Models.MachineOperationRecord", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("LaserCutConfiguration");

                    b.Navigation("MachineAlarms");
                });

            modelBuilder.Entity("MachineMonitoring.Infrastructure.Persistence.Models.ProductionLotRecord", b =>
                {
                    b.Navigation("Workpieces");
                });

            modelBuilder.Entity("MachineMonitoring.Infrastructure.Persistence.Models.WorkpieceRecord", b =>
                {
                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
